name: Continuous Integration

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: sudo apt -q install dosbox
    - name: build
      run: |
        ./build/watbuild.sh
        mkdir -p artifacts
        cp *.EXE artifacts
    - name: test
      run: ./test/runtests.sh
    - name: Upload EXEs
      uses: actions/upload-artifact@v1
      with:
        path: "artifacts"
        name: vutils
