name: Continuous Integration

on: [push, pull_request]

jobs:
  watcom_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: sudo apt -q install dosbox
    - name: build
      run: |
        ./build/watbuild.sh
        mkdir -p artifacts
        cp *.EXE artifacts
    - name: test
      run: ./test/runtests.sh
      timeout-minutes: 10
    - name: Find Git version
      id: version
      run: |
        export VERSION=$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Upload EXEs
      uses: actions/upload-artifact@v1
      with:
        path: "artifacts"
        name: vanilla-utilities-${{steps.version.outputs.VERSION}}

  turboc_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: sudo apt -q install dosbox
    - name: build
      run: |
        ./build/tcbuild.sh
    - name: test
      run: ./test/runtests.sh
      timeout-minutes: 10
