name: Continuous Integration

on: [push, pull_request, workflow_dispatch]

jobs:
  code_health_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install tools
      run: |
        sudo apt update
        sudo apt -q install clang-format
    - name: Run checks
      run: |
        clang-format -i */*.[ch]
        git diff > formatting-fixes.diff
        if ! grep "" formatting-fixes.diff; then
          rm -f formatting-fixes.diff
        else
          (echo "Formatting errors detected by clang-format. Please run" \
                "\`clang-format -i */*.[ch]\` or apply" \
                "formatting-fixes.diff below.";
           echo) >> $GITHUB_STEP_SUMMARY
          false
        fi
    - uses: actions/upload-artifact@v6
      if: '!cancelled()'
      with:
        if-no-files-found: ignore
        name: formatting-fixes.diff
        path: formatting-fixes.diff
